name: Wiki
on:
  push:
    paths:
      - 'wiki/**'
      - src/rez/rezconfig.py
  pull_request:
    paths:
      - 'wiki/**'
      - src/rez/rezconfig.py
env:
  CLONE_URL: "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git"

jobs:
  build:
    name: Build Wiki Artifact
    runs-on: ubuntu-latest
    env:
      TEMP_WIKI_DIR: "wiki/.rez-gen-wiki-tmp"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build Wiki
        working-directory: wiki  # Start in correct dir, else inspect fails
        run: |
          git config --global color.ui always
          if [ "${{ github.event_name == 'pull_request' }}" == "true" ]
          then
            BRANCH="${{ github.head_ref }}"
          else
            BRANCH="${{ github.ref }}"
          fi

          python update-wiki.py \
            --keep-temp \
            --no-push \
            --github-release="$BRANCH" \
            --github-branch="${BRANCH##refs*/}" \
            --wiki-dir="${{ github.workspace }}"/"${{ env.TEMP_WIKI_DIR }}" \
            --wiki-url="${{ env.CLONE_URL }}"

      - uses: actions/upload-artifact@v1.0.0
        with:
          name: wiki-markdown
          path: ${{ env.TEMP_WIKI_DIR }}


  publish:
    name: Publish to GitHub Wiki
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: wiki-markdown
          path: .

      - name: Setup git config
        run: |
          git config --global color.ui always
          git config --global user.name "github.com/${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@${{ github.sha }}"

      - name: Git commit and push
        run: |
          git commit \
              -m "Generated from GitHub "${{ github.workflow }}" Workflow" \
              -m "See https://github.com/${{ github.repository }}/runs/${GITHUB_ACTION}" \
              || exit 0
          git remote set-url origin "${{ env.CLONE_URL }}"
          git push origin master
